### ISSUE TITLE
Manual de instalación de SonarQube

### ISSUE THREAD

**Issue by dag0035** [bmg0039/GESPRO_Practicas#14]
Anexo de la memoria En Open shift En Local

**Comment by bmg0039** [comment]
Adjunto el anexo Manual de Usuario, en el que se explica cómo desplegar la instancia de SonarQube en local y en la plataforma OpenShift, cómo analizar un proyecto y la instalación de todas las herramientas utilizadas en los dos procesos anteriores.

[Manual de usuario.pdf](https://github.com/bmg0039/GESPRO_Practicas/files/574890/Manual.de.usuario.pdf)

**Comment by dag0035** [comment]
Revisión de manual de usuario. Complementarla con la entregada en papel.

[RevPlammenManual de usuario.pdf](https://github.com/bmg0039/GESPRO_Practicas/files/574889/RevPlammenManual.de.usuario.pdf)
