### ISSUE TITLE
 Crear anexo Manual del Administrador

### ISSUE THREAD

**Issue by dag0035** [bmg0039/GESPRO_Practicas#16]
Crear un manual del administrador con la parte de instalación y despliegue de la instancia de SonarQube, descrita en el manual de usuario. Incluir una descripción de las configuraciones realizadas.

**Comment by bmg0039** [comment]
Creado el anexo Manual del Administrador en el que se explica como configurar los ficheros de SonarQube y desplegar la instancia en la plataforma OpenShift.
[anexo-maunal-administrador.pdf](https://github.com/bmg0039/GESPRO_Practicas/files/574907/anexo-maunal-administrador.pdf)
