### ISSUE TITLE
Manual para escanear un proyecto

### ISSUE THREAD

**Issue by bmg0039** [bmg0039/GESPRO_Practicas#17]
Hablar de los ficheros de configuración dependiendo del lenguaje
Comprobar la ejecución de Test Interesante un video tutorial ActivePresenter en Windows

**Comment by dag0035** [comment]
Corregidos fallos en el manual de usuario en el que se explica como realizar análisis de proyectos con los distintos scanner de SonarQube

**Comment by bmg0039** [comment]
Adjunto revisión con comentarios pdf
[revclopezno_anexo-manual-usuario.pdf](https://github.com/bmg0039/GESPRO_Practicas/files/574904/revclopezno_anexo-manual-usuario.pdf)

**Comment by bmg0039** [comment]
He probado los manuales de usuario referentes a SonarQube Scanner y SonarQube Scanner for MSBuild y siguiendo sus pasos he conseguido escanear los proyectos de la primera convocatoria (PHP. Java y C#). He dejado los resultados en la instancia de    http://tfgqa-ubugii.rhcloud.com/dashboard/

Creo que es la mejor forma de probar la calidad de tu documentación ;-)
