### ISSUE TITLE
Crear trabajos relacionados de la memoria

### ISSUE THREAD

**Issue by dag0035** [bmg0039/GESPRO_Practicas#22]
Comparar a nivel funcional con OpenHub [https://www.openhub.net/](url) Añadir una tabla comparativa.

**Comment by bmg0039** [comment]
Adjunto el apartado Trabajos Relacionados de la memoria
[memoria_trabajos_relacionados.pdf](https://github.com/bmg0039/GESPRO_Practicas/files/578639/memoria_trabajos_relacionados.pdf)

**Comment by bmg0039** [comment]
Tarea realizada.
