### ISSUE TITLE
 Apéndice B: Especificación de Requisitos

### ISSUE THREAD

**Issue by dag0035** [bmg0039/GESPRO_Practicas#27]
Crear la documentación correspondiente al apéndice Especificación de Requisitos

**Comment by dag0035** [comment]
Adjunto la documentación correspondiente al apéndice Especificación de Requisitos
[anexos_especificacion_requisitos.pdf](https://github.com/bmg0039/GESPRO_Practicas/files/587912/anexos_especificacion_requisitos.pdf)

**Comment by bmg0039** [comment]
Tarea realizada.
