### ISSUE TITLE
Documentación sección técnicas y herramientas

### ISSUE THREAD

**Issue by bmg0039** [bmg0039/GESPRO_Practicas#7]
Indicar una visión general de la herramienta. Descripción funcional breve. Para qué se utiliza en la herramienta en el proyecto y referenciar a Web o libro.
SonarQube OpenShift
Jira Issues
Git IntelliJ Java LateX ....

[clopezno_memoria_tecnicas_herramientas.pdf](https://github.com/bmg0039/GESPRO_Practicas/files/574769/clopezno_memoria_tecnicas_herramientas.pdf)

[memoria_tecnicas_herramientas.pdf](https://github.com/bmg0039/GESPRO_Practicas/files/574772/memoria_tecnicas_herramientas.pdf)

**Comment by bmg0039** [comment]
Adjunto una versión provisional del apartado Técnicas y Herramientas de la memoria.
[memoria_tecnicas_herramientas (1).pdf](https://github.com/bmg0039/GESPRO_Practicas/files/574775/memoria_tecnicas_herramientas.1.pdf)

**Comment by dag0035** [comment]
Adjunto una revisión con comentarios sobre el pdf.

[clopezno_memoria_tecnicas_herramientas.pdf](https://github.com/bmg0039/GESPRO_Practicas/files/574769/clopezno_memoria_tecnicas_herramientas.pdf)
