### ISSUE TITLE
 Despliegue de instancia local de SonarQube

### ISSUE THREAD

**Issue by dag0035** [bmg0039/GESPRO_Practicas#9]
Despliegue de una instancia local de la herramienta SonarQube en la que se muestran los proyectos analizados. La instancia local es resultado de ejecutar una aplicación autónoma, sin necesidad de realizar ninguna instalación.

**Comment by dag0035** [comment]
Requisitos para poder desplegar la instancia de SonarQube de forma local:
Entorno de ejecución de Java (en mi caso Oracle JRE)
Navegador Web para acceder al entorno de SonarQube (en mi caso Google Chrome)

**Comment by bmg0039** [comment]
Tarea terminada
